name: Check links

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/workflows/check_links_config.json"
